# Generated by Django 6.0.7 on 2026-07-11 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.CharField(max_length=50, unique=True, verbose_name="numéro d'ordre")),
                ('specialite', models.CharField(max_length=100, verbose_name='spécialité')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('actif', 'Actif'), ('suspendu', 'Suspendu')], default='en_attente', max_length=12, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'médecin',
                'verbose_name_plural': 'médecins',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddn', models.DateField(verbose_name='date de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='groupe sanguin')),
                ('allergies', models.JSONField(blank=True, default=list, verbose_name='allergies')),
                ('antecedents', models.JSONField(blank=True, default=list, verbose_name='antécédents')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_crees', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
            },
        ),
    ]
