# Generated by Django 6.0.7 on 2026-07-12 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('date_expiration', models.DateField(verbose_name="date d'expiration")),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances_prescrites', to=settings.AUTH_USER_MODEL, verbose_name='médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='medical.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'ordonnance',
                'verbose_name_plural': 'ordonnances',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrdonnanceLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200, verbose_name='médicament')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='dosage')),
                ('frequence', models.CharField(blank=True, max_length=100, verbose_name='fréquence')),
                ('duree', models.CharField(blank=True, max_length=100, verbose_name='durée')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='medical.ordonnance', verbose_name='ordonnance')),
            ],
            options={
                'verbose_name': "ligne d'ordonnance",
                'verbose_name_plural': "lignes d'ordonnance",
                'ordering': ['id'],
            },
        ),
    ]
