# Generated by Django 6.0.7 on 2026-07-12 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_ordonnance_ordonnanceligne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('heure', models.TimeField(verbose_name='heure')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='motif')),
                ('salle', models.CharField(blank=True, max_length=50, verbose_name='salle')),
                ('statut', models.CharField(choices=[('confirme', 'Confirmé'), ('annule', 'Annulé')], default='confirme', max_length=10, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous_planifies', to=settings.AUTH_USER_MODEL, verbose_name='médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='medical.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'rendez-vous',
                'verbose_name_plural': 'rendez-vous',
                'ordering': ['-date', '-heure'],
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('type', models.CharField(choices=[('biologie', 'Biologie'), ('imagerie', 'Imagerie'), ('microbiologie', 'Microbiologie')], default='biologie', max_length=15, verbose_name='type')),
                ('intitule', models.CharField(max_length=200, verbose_name='intitulé')),
                ('valeur', models.CharField(blank=True, max_length=100, verbose_name='valeur')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('statut', models.CharField(choices=[('normal', 'Normal'), ('limite', 'Limite'), ('eleve', 'Élevé'), ('bas', 'Bas')], default='normal', max_length=10, verbose_name='statut')),
                ('laboratoire', models.CharField(blank=True, max_length=150, verbose_name='laboratoire')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_saisis', to=settings.AUTH_USER_MODEL, verbose_name='médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='medical.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': "résultat d'examen",
                'verbose_name_plural': "résultats d'examen",
                'ordering': ['-date', '-id'],
            },
        ),
    ]
