# Generated by Django 6.0.7 on 2026-07-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='adresse e-mail')),
                ('date_installation', models.DateTimeField(auto_now_add=True, verbose_name="date d'installation")),
            ],
            options={
                'verbose_name': 'établissement',
                'verbose_name_plural': 'établissement',
            },
        ),
    ]
