# Generated by Django 6.0.7 on 2026-07-15 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_etablissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('maintenance', 'Maintenance')], default='ouvert', max_length=12, verbose_name='statut')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.etablissement', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['nom'],
            },
        ),
    ]
