# Generated by Django 6.0.7 on 2026-07-11 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGIN_ECHEC', 'Échec de connexion'), ('LOGOUT', 'Déconnexion'), ('INSTALLATION', 'Installation'), ('CHANGEMENT_MDP', 'Changement de mot de passe')], max_length=30, verbose_name='action')),
                ('identifiant_saisi', models.CharField(blank=True, max_length=150, verbose_name='identifiant saisi')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='détail')),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='horodatage')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "journal d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-horodatage'],
            },
        ),
    ]
