# Generated by Django 6.0.7 on 2026-07-11 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='patient_concerne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='medical.patient', verbose_name='patient concerné'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGIN_ECHEC', 'Échec de connexion'), ('LOGOUT', 'Déconnexion'), ('INSTALLATION', 'Installation'), ('CHANGEMENT_MDP', 'Changement de mot de passe'), ('CREATION_MEDECIN', "Création d'un compte médecin"), ('VALIDATION_MEDECIN', "Validation d'un compte médecin"), ('SUSPENSION_MEDECIN', "Suspension d'un compte médecin"), ('CREATION_DOSSIER', "Création d'un dossier patient"), ('GENERATION_CODE', "Génération d'un code d'accès"), ('ACCES_ACCORDE', 'Accès accordé'), ('CODE_ECHEC', "Échec de validation d'un code"), ('ACCES_DOSSIER', 'Accès au dossier'), ('ACCES_REFUSE', 'Accès refusé'), ('REVOCATION_ACCES', "Révocation d'un accès")], max_length=30, verbose_name='action'),
        ),
    ]
