# Generated by Django 6.0.7 on 2026-07-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGIN_ECHEC', 'Échec de connexion'), ('LOGOUT', 'Déconnexion'), ('INSTALLATION', 'Installation'), ('CHANGEMENT_MDP', 'Changement de mot de passe'), ('MODIFICATION_PROFIL', 'Modification du profil'), ('CREATION_MEDECIN', "Création d'un compte médecin"), ('VALIDATION_MEDECIN', "Validation d'un compte médecin"), ('SUSPENSION_MEDECIN', "Suspension d'un compte médecin"), ('CREATION_DOSSIER', "Création d'un dossier patient"), ('DEMANDE_ACCES', "Demande d'accès envoyée"), ('APPROBATION_ACCES', "Demande d'accès approuvée"), ('REFUS_ACCES', "Demande d'accès refusée"), ('ACCES_DOSSIER', 'Accès au dossier'), ('ACCES_REFUSE', 'Accès refusé'), ('REVOCATION_ACCES', "Révocation d'un accès"), ('AJOUT_ORDONNANCE', "Ajout d'une ordonnance"), ('AJOUT_RESULTAT', "Ajout d'un résultat d'examen"), ('AJOUT_RENDEZVOUS', "Ajout d'un rendez-vous")], max_length=30, verbose_name='action'),
        ),
    ]
