# Generated by Django 6.0.7 on 2026-07-11 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('creation', 'Création du dossier'), ('code', "Code d'autorisation")], max_length=10, verbose_name='source')),
                ('accorde_le', models.DateTimeField(auto_now_add=True, verbose_name='accordé le')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('revoque', models.BooleanField(default=False, verbose_name='révoqué')),
                ('revoque_le', models.DateTimeField(blank=True, null=True, verbose_name='révoqué le')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_accordes', to=settings.AUTH_USER_MODEL, verbose_name='médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces', to='medical.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'accès',
                'verbose_name_plural': 'accès',
                'ordering': ['-accorde_le'],
            },
        ),
        migrations.CreateModel(
            name='CodeAutorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, verbose_name='code (haché)')),
                ('duree_heures', models.PositiveSmallIntegerField(choices=[(24, '24 heures'), (48, '48 heures'), (72, '72 heures'), (168, '7 jours')], verbose_name="durée de l'accès accordé")),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('utilise', models.BooleanField(default=False, verbose_name='utilisé')),
                ('utilise_le', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_autorisation', to='medical.patient', verbose_name='patient')),
                ('utilise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_utilises', to=settings.AUTH_USER_MODEL, verbose_name='utilisé par')),
            ],
            options={
                'verbose_name': "code d'autorisation",
                'verbose_name_plural': "codes d'autorisation",
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=200, verbose_name='motif')),
                ('diagnostic', models.CharField(blank=True, max_length=300, verbose_name='diagnostic')),
                ('traitement', models.CharField(blank=True, max_length=300, verbose_name='traitement')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('ta', models.CharField(blank=True, max_length=20, verbose_name='tension artérielle')),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SpO2 (%)')),
                ('date_consultation', models.DateTimeField(auto_now_add=True, verbose_name='date de consultation')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_realisees', to=settings.AUTH_USER_MODEL, verbose_name='médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='medical.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'ordering': ['-date_consultation'],
            },
        ),
    ]
