# Generated by Django 6.0.7 on 2026-07-12 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acces',
            name='source',
            field=models.CharField(choices=[('creation', 'Création du dossier'), ('demande', 'Demande approuvée')], max_length=10, verbose_name='source'),
        ),
        migrations.CreateModel(
            name='DemandeAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('consultation', 'Consultation médicale'), ('urgence', 'Urgence médicale'), ('bilan', 'Bilan de santé'), ('suivi', 'Suivi de traitement')], max_length=20, verbose_name='motif')),
                ('duree_heures', models.PositiveSmallIntegerField(choices=[(24, '24 heures'), (48, '48 heures'), (72, '72 heures'), (168, '7 jours')], verbose_name='durée souhaitée')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_attente', max_length=12, verbose_name='statut')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('repondu_le', models.DateTimeField(blank=True, null=True, verbose_name='répondue le')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_acces', to='medical.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': "demande d'accès",
                'verbose_name_plural': "demandes d'accès",
                'ordering': ['-cree_le'],
            },
        ),
        migrations.DeleteModel(
            name='CodeAutorisation',
        ),
    ]
